server.port=8080

spring.application.name=apigateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.discovery.locator.enabled=true

# userservice
spring.cloud.gateway.server.webmvc.routes[0].id=userservice
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://userservice
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**

# authservice
spring.cloud.gateway.server.webmvc.routes[1].id=authservice
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://authservice
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**

# adminservice
spring.cloud.gateway.server.webmvc.routes[2].id=adminservice
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://adminservice
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/admin/**

# bookingservice
spring.cloud.gateway.server.webmvc.routes[3].id=bookingservice
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://bookingservice
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/bookings/**

# workerservice
spring.cloud.gateway.server.webmvc.routes[4].id=workerservice
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://workerservice
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/workers/**

# notificationservice
spring.cloud.gateway.server.webmvc.routes[5].id=notificationservice
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://notificationservice
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/notifications/**

# paymentservice
spring.cloud.gateway.server.webmvc.routes[6].id=paymentservice
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://paymentservice
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/payments/**

# xpservice
spring.cloud.gateway.server.webmvc.routes[7].id=xpservice
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://xpservice
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/xp/**

# assignmentservice
spring.cloud.gateway.server.webmvc.routes[8].id=assignmentservice
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://assignmentservice
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/assignments/**
